#! /bin/sh
### BEGIN INIT INFO
# Provides:          Agilium NG Server
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Agilium NG Server
# Description:       Agilium NG Server
### END INIT INFO
 
### service installer will place here DIR variable containing the path to cohorte node
DIR=/home/pi/cohorte/demos/led-raspberry-gpio

DAEMON=$DIR/bin/daemon_unix.py
DAEMON_CONF_FILE=$DIR/conf/daemon.conf

# init context variables
COHORTE_BASE=$DIR
COHORTE_BASE=${COHORTE_BASE#\"}
COHORTE_BASE=${COHORTE_BASE%\"}
COHORTE_HOME=`cat $DAEMON_CONF_FILE | grep COHORTE_HOME | cut -d\= -f 2`
COHORTE_HOME=${COHORTE_HOME#\"}
COHORTE_HOME=${COHORTE_HOME%\"}
PYTHON_INTERPRETER=`cat $DAEMON_CONF_FILE | grep PYTHON_INTERPRETER | cut -d\= -f 2`
PYTHON_INTERPRETER=${PYTHON_INTERPRETER#\"}
PYTHON_INTERPRETER=${PYTHON_INTERPRETER%\"}
DAEMON_NAME=`cat $DAEMON_CONF_FILE | grep NODE_NAME | cut -d\= -f 2`
DAEMON_NAME=${DAEMON_NAME#\"}
DAEMON_NAME=${DAEMON_NAME%\"}

DAEMON_USER=`cat $DAEMON_CONF_FILE | grep DAEMON_USER | cut -d\= -f 2`
DAEMON_USER=${DAEMON_USER#\"}
DAEMON_USER=${DAEMON_USER%\"}

# Add any command line options for your daemon here
DAEMON_OPTS="--cohorte-home $COHORTE_HOME --cohorte-base $COHORTE_BASE --python-interpreter $PYTHON_INTERPRETER"
 

 
# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid
 
. /lib/lsb/init-functions
 
do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    echo $DAEMON_USER
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON -- $DAEMON_OPTS
    log_end_msg $?
}
do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    #start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $DAEMON_NAME
    log_end_msg $?
}
 
case "$1" in
 
    start|stop)
        do_${1}
        ;;
 
    restart|reload|force-reload)
        do_stop
        do_start
        ;;
 
    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
 
esac
exit 0
