#!/bin/bash
export COHORTE_HOME=/opt/cohorte-1.1.2
export COHORTE_BASE=/opt/led-gateway
export COHORTE_APP_ID=led
export JAVA_HOME=/opt/java
export PATH="$PATH:$JAVA_HOME/bin"
bash $COHORTE_HOME/bin/cohorte-start-node --base $COHORTE_BASE --use-config run.js -d -v -c --app-id $COHORTE_APP_ID $* &